### ISSUE TITLE
A question on stackoverflow

### ISSUE THREAD

**Issue by protonfucker** [dthree/cash#109]
Hello, dthree, this is not a issue about the cash, but i want to ask something about http://serverfault.com/questions/561399/port-forwarding-stops-abruptly-windows-server-2012,
I encounter the same question as you have, I really want to know how you solve it. Thx very much

**Comment by nfischer** [comment]
@protonfucker @dthree isn't terribly active on Github right now, so I don't know if he'll see this post. I'm closing this, since it doesn't have anything to do with Cash. If he sees this, he can respond on the stackoverflow post or in another comment on this issue.

**Comment by dthree** [comment]
HI @protonfucker 

I never did resolve it. It's either bad hardware (try another NIC), or that Windows port forwarding wasn't meant for production environments with a heavy load.

It seems to trigger during intense network usage from a lot of sources at the same time, which makes it wig out.

My recommendation is: don't do it.
