### ISSUE TITLE
[PROPOSAL] Clear command

### ISSUE THREAD

**Issue by lahaxearnaud** [dthree/cash#12]
Hello,

Can you please add clear support.

Have a good day,

Arnaud

**Comment by naholyr** [comment]
* Windows: ``CLS``
* Mac/Linux AFAIK: ``clear``

Is it enough to cover it up?

**Comment by dthree** [comment]
Sure! Please go to the roadmap pants in the wiki, add clear and vote on it. Great suggestion though!
