### ISSUE TITLE
Cash not running commands outside of included commands

### ISSUE THREAD

**Issue by ItsJamie9494** [dthree/cash#122]
cash Will not run a command outside of the included ones. If I try to run, for example, npm, it just shows the help menu. Yet, running echo works just fine, because it's built in.

**Comment by nfischer** [comment]
Which OS are you using? I believe external commands are still only supported on Windows.

**Comment by ItsJamie9494** [comment]
Linux

**Comment by nfischer** [comment]
#123 just about implements this. I didn't try writing tests yet, just hacked something together.

**Comment by ItsJamie9494** [comment]
#123 looks good, I added it onto a local copy of cash I have, and commands like npm are running just fine.
