### ISSUE TITLE
cd not working properly with tab functionality

### ISSUE THREAD

**Issue by younesbram** [dthree/cash#127]
installed cash with npm,
typed cash in windows, ls works looks good everything.
when i type in ` cd New ` and hit tab, it goes to `cd New Folder/` , however this creates a bug:
`no such file or directory chdir C:\whatever -> 'New'`
obviously easy fix just to add an apostrophe ( ' ) to make it a string but, please fix this can just make it always take in the whole thing and stringify input when its cd.

**Comment by nfischer** [comment]
I think this is a duplicate of #32. There are a few known issues around tab completion.
