### ISSUE TITLE
How do I change Volume on Windows ?

### ISSUE THREAD

**Issue by warpdesign** [dthree/cash#13]
Say I start cash from c:\foo

Typing `cd /` will go to `c/` which is the root of `C:\` but it seems there is no way to change drive: typing `cd /e` to go to e:\ as in cygwin doesn't work.

Is there a way to change drive ?

**Comment by dthree** [comment]
Thanks for pointing this out. Will check out.

**Comment by warpdesign** [comment]
I noticed that typing `cd e:` works, but it doesn't sound really Unix.

**Comment by dthree** [comment]
You're right. This should be a quick fix.

**Comment by dthree** [comment]
Should be good now :+1:
