### ISSUE TITLE
Replace lodash with ESX equivalents

### ISSUE THREAD

**Issue by blockloop** [dthree/cash#15]
Typically I avoid bring up the tired discussion of "you might not need underscore," but this project boasts being "written in pure ES6." That being said, when searching through some of the source code I discovered some basic usages of lodash. Curiosity got the best of me so I grepped this directory for usages of lodash and found the following unique cases

```
_.extend
_.filter
_.isArray
_.isObject
_.isString
_.map
_.remove
_.toArray
```

Usages of extend, filter, isArray, map, remove, and toArray can be replaced by built-in features of JavaScript (some much older than ES6). The others (isString and isObject) have simple, one line equivalents. Are you opposed to removing lodash and using the builtin features? If you're okay with it, I'd can submit a PR.

**Comment by blockloop** [comment]
To be more clear on the replacements

`extend` = [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)
`filter` = [arrayInstance.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)
`isArray` = [Array.isArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)
`map` = [arrayInstance.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)
`toArray` = [Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

The other, non-builtins are

isObject = `(typeof obj === "object") && (obj !== null)`
isString = `(typeof obj === 'string' || obj instanceof String)`
remove = `var index = array.indexOf(item); array.splice(index, 1);`

You can avoid repetition by putting those last three in a `util.js` file, but putting them inline is arguably less obscure.

**Comment by dthree** [comment]
I don't mind switching over. However, Cash depends on Vorpal, which depends on Inquirer.js, and each of those use lodash, so I'm not going to eliminate the dependency (I actually tried very hard, and couldn't get agreement). But I wouldn't mind some help switching out to ESX equivalents!

**Comment by blockloop** [comment]
Cool. I'll start hacking on that this evening. Would you rather me use inline replacements of the latter three or use a `util.js` and use `util.isObject(obj)`?

**Comment by dthree** [comment]
Thanks!!

Just do inline, unless one file has like 10, then make a function in the file. If we're minimizing deps for a given file, lets minimize deps :)

**Comment by blockloop** [comment]
:1 Sounds good to me

**Comment by dthree** [comment]
:+1:

**Comment by dthree** [comment]
:+1:

**Comment by warpdesign** [comment]
+1 on this one. If you need help @blockloop I can do that.

**Comment by blockloop** [comment]
@dthree thank you for using `npm test` :). It saved me a lot of time.

**Comment by dthree** [comment]
@blockloop merged. You're the best.
