### ISSUE TITLE
What are the advantages compared with windows PowerShell

### ISSUE THREAD

**Issue by ShangXinbo** [dthree/cash#18]
With windows 10 , microsolf made a windows PowerShell，I think powerShell is good.What are the advantages compared with windows PowerShell

**Comment by dthree** [comment]
You can use Cash in Powershell. It's in the main the commands - powershell does not implement all of the Linux coreutils, that's what Cash aims to do.

Does that answer your question?

**Comment by ShangXinbo** [comment]
thanks

**Comment by dthree** [comment]
:+1:
