### ISSUE TITLE
Dear dthree,what command will the future version add? 

### ISSUE THREAD

**Issue by zxx1988328** [dthree/cash#19]
Cash works well in my Win7 pc.Thanks for sharing.
And what command wiil add in the future  ? Like delete a  directory or vim the file.
Dear dthree,which language you use to develop the "Cash".

**Comment by dthree** [comment]
Great! 
Check out the roadmap page in the wiki for future commands.
Cash was developed in pure JavaScript.

**Comment by zxx1988328** [comment]
thanks for your answer

**Comment by dthree** [comment]
:+1:
