### ISSUE TITLE
Error while installing on Windows 10 

### ISSUE THREAD

**Issue by Krossfade** [dthree/cash#2]
Here's the debug log
[npm-debug.txt](https://github.com/dthree/cash/files/141585/npm-debug.txt)

**Comment by dthree** [comment]
Thanks. Looks like it might be a problem on Node `v0.12.0`. Could you try it on `4` or `5`?

**Comment by Krossfade** [comment]
Using Node `v4.3.1` seemed to work. Thanks!

**Comment by dthree** [comment]
:+1:

**Comment by RangerMauve** [comment]
Weird. I actually got it running on win 10 with node 0.11.16

**Comment by dthree** [comment]
Huh. Interesting. I just have to get rid of ES6 in the global `preinstall` and `postinstall` scripts - no biggie, and then it should work x-platform.
