### ISSUE TITLE
Q: Does cash read some init file?

### ISSUE THREAD

**Issue by kgrossjo** [dthree/cash#20]
Does cash read some init file when it starts up?  Like bash reading `~/.bashrc`?

**Comment by dthree** [comment]
Not currently. What are your suggested use cases?

**Comment by nfischer** [comment]
This would be a cool feature down the road. This would be a way to add in user aliases that are run at startup (like aliasing ls to always have colored output). If cash is meant as a substitute for Cygwin and the like, reading some sort of startup file would be a necessity (~/.bashrc, ~/.cashrc, ~/_cashrc, whatever). I think opting with ~/.cashrc is the way to go (and maybe ~/_cashrc for Windows systems).

Does cash have support for `source`? This would be necessary before an init file can be used.

**Comment by dthree** [comment]
:+1: 

On source, not yet. You can throw it into the Roadmap:

https://github.com/dthree/cash/wiki/Roadmap

**Comment by nfischer** [comment]
Will do :+1:

**Comment by nfischer** [comment]
@kgrossjo I implemented a crude approach to an init file in #50. This might be good enough for an initial version, although I'll happily take suggestions into account.

**Comment by shannonmoeller** [comment]
To the implementer of this feature, please include `~/.config/cash` support in addition to `~/.cahsrc`.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html

**Comment by dthree** [comment]
@shannonmoeller will do

**Comment by nfischer** [comment]
The way this is implemented currently is that file will be `~/.cashrc` (unix) or `%HOMEPATH%\_cashrc` (Windows).

**Comment by dthree** [comment]
@nfischer is the Windows `_cashrc` based on any standard? I did a bit of googling on dotfiles on Windows, and can't find anyone using underscores. I don't want to make another standard...

https://xkcd.com/927/

Can we discuss?

@shannonmoeller looking at this again, I don't know that we're going to do this as bash doesn't include this as an option. I'm trying to have cash mirror bash as much as possible, and it seems this is a convenient preference against a dis-related standard. Unless I'm wrong and missing something?

**Comment by nfischer** [comment]
@dthree:

> @nfischer is the Windows _cashrc based on any standard? I did a bit of googling on dotfiles on Windows, and can't find anyone using underscores. I don't want to make another standard...

This is based on vim, which searches for `_vimrc` and `_gvimrc` on Windows. See [this page](http://vimdoc.sourceforge.net/htmldoc/starting.html#initialization) from the vim help:

> ```
> 	Recommended place for your personal initializations:
> 		Unix		    $HOME/.vimrc
> 		OS/2		    $HOME/.vimrc or $VIM/.vimrc (or _vimrc)
> 		MS-DOS and Win32    $HOME/_vimrc or $VIM/_vimrc
> 		Amiga		    s:.vimrc or $VIM/.vimrc
> ```

Alternative approaches I wouldn't be opposed to:

 1. Always search for `~/.cashrc`
 2. Always search for either `~/.cashrc` or `~/_cashrc`, preferring one over the other (either way is fine)

**Comment by dthree** [comment]
Okay good I agree. Mid implementing this on Windows, push coming soon.

**Comment by nfischer** [comment]
:+1:

**Comment by dthree** [comment]
This is done now. 

https://github.com/dthree/cash/commit/963be43ddbaa18dba46ef5a101a62c2ee431cde0

On windows `_cashrc` and `.cashrc` are supported.
