### ISSUE TITLE
How to show environment variables - bug?

### ISSUE THREAD

**Issue by u02sgb** [dthree/cash#22]
Hi,
  I can't get `cash` to show Environment variables in `cmd.exe` or `powershell` when I use `echo`.

`cmd.exe`:
```
echo %ORACLE_HOME%
e:\oracle\product\11.2.0\client_1
cash
me@myserver:I/$ echo $ORACLE_HOME
$ORACLE_HOME
me@myserver:I/$ echo %ORACLE_HOME%
%ORACLE_HOME%
```
`powershell` (similar results to above)

Cheers,
  Stuart.

**Comment by dthree** [comment]
Fixed.

https://github.com/dthree/cash/commit/ced6ce6233ebeaa6fa3a82248df83547991fb665

**Comment by u02sgb** [comment]
Thanks for such a quick fix!  I'm a bit new to all of this, how long would it normally take for this fix to be available via and `npm update -g cash`?

**Comment by dthree** [comment]
I published last night.

You can always check npm for the last release
