### ISSUE TITLE
Support for globbing?

### ISSUE THREAD

**Issue by nfischer** [dthree/cash#25]
Just tried this out with `npm install -g cash` on my Ubuntu box with node 5.3. It seems pretty cool! I couldn't get any support for globbing, however. Not sure if this is a bug, or if it hasn't been implemented yet. I saw that you're using the glob module in package.json, but I was surprised that the CLI didn't offer support for it.

**Comment by dthree** [comment]
Can you give me a usage example? Individual commands support it well.

**Comment by nfischer** [comment]
Here's what I tried

```Bash
bash $ cash
cash $ ls
node_modules  package.json
cash $ ls *.json
cash $
```

As you can see, there is no output after I run `ls *.json`, whereas the standard bash utility would output `package.json`.

Also, as a side note, are you adding support for comments? I tried annotating my example with `ls *.json # this has no output`, but when I actually typed that, I realized that it I get even weirder behavior:

```Bash
cash $ ls *.json # no ouptut
*.json:


#:


no:


ouptut:

```

**Comment by dthree** [comment]
Thanks. Looks like I didn't implement globbing for `ls`. It's easy to add, so will do soon! 

It's by command - try `grep a *.json` and that will work, for example.

---

I've got a bit to do on `bash` implementation, but will definitely be implementing comments and all the rest.

**Comment by nfischer** [comment]
Have you thought about globbing at the shell level, instead of in individual commands? ShellJS was previously doing it for each command, but I felt like that was always fighting with bash compatibility. In traditional shells, all globbing happens in the shell itself (so `ls` never sees `*.json`, it actually sees `package.json`).

**Comment by dthree** [comment]
You have me thinking about it now :smile: 

That's a good idea. Will do.

**Comment by dthree** [comment]
Here's the start of the pre-parser, btw. So far `%ENV_VARIABLE%` translation goes in by default for Windows users.

https://github.com/dthree/cash/blob/master/src/preparser.js

**Comment by dthree** [comment]
Glob is now working for `ls` in the latest release.

---

I didn't add it to the `preparser` yet, as I would like to discuss this with you. Not all commands should accept globs, and if a different type of parameter than files are expected, this could cause some weird behavior.

Perhaps we could pass in a parameter to the `preparser` like `glob: true`, and then normalize all input parsing for those commands.

**Comment by nfischer** [comment]
> Glob is now working for ls in the latest release.

:+1:

We recently adjusted this at ShellJS. In 0.6, only certain commands accept globs (ex. `rm()`, `ls()`, etc.). I modified this so that globbing (performed by `common.expand()`) happens inside `common.wrap()` (see [here](https://github.com/shelljs/shelljs/blob/master/src/common.js#L274-L275)). `common.wrap()` is our approximation of the "shell," in a sense.

In a true shell, all the globbing happens by default. So you can do weird things, such as:

```Bash
$ touch mkdir # create some file named, which has the same name as a unix command
$ which mk* # let's assume that `mkdir` is our only file
/bin/mkdir
$ echo *ir
mkdir
```

These are two examples of commands you wouldn't normally want to glob. To be consistent with bash, however, you would need to support globbing for them. In ShellJS, we disable globbing (for performance reasons/it isn't a very useful feature).

**Comment by dthree** [comment]
Huh. Interesting. 

Alright, will keep this in mind as Cash matures, and we'll see!

**Comment by nfischer** [comment]
Sounds good
