### ISSUE TITLE
wiki update

### ISSUE THREAD

**Issue by GottZ** [dthree/cash#3]
hey!

sadly github still does not support pull requests to wiki pages.

there you can see what i changed:

https://github.com/GottZ/cash/wiki/Roadmap
https://github.com/GottZ/cash/wiki/Roadmap/_compare/2fb63f099d3bebfd04198c1c22f677863f255725...b4817ea734afb9f189359fc4009dff961c0293e3

greetings

PS:
easiest would be to pull mine and push it to yours.

**Comment by dthree** [comment]
Err... The beauty of wiki is that you can edit without forking. Just go to the main wiki and click edit.

**Comment by dthree** [comment]
Closing this, but if you have any trouble, let me know!

**Comment by dthree** [comment]
My bad, @GottZ I had wiki set to uneditable! Try now, you should be able to add content.
