### ISSUE TITLE
`touch -c file.txt` doesn't work

### ISSUE THREAD

**Issue by nfischer** [dthree/cash#40]
I tried running:

```Bash
cash $ touch -c file.txt


  Missing required argument. Showing Help:

  Usage: touch [options] <files...>


  Options:

    --help                  output usage information
    -a                      change only the access time
    -c, --no-create         do not create any files
    -d, --date [STRING]     parse STRING and use it instead of current time
    -m                      change only the modification time
    -r, --reference [FILE]  use this file's times instead of current time
    --time [WORD]           change the specified time: WORD is access, atime, or use: equivalent to -a WORD is modify or mtime: equivalent to -m
```

This doesn't seem to be the correct output. This happens whether the file I specify exists or doesn't exist.

Also, if I run this:

```Bash
cash $ touch -c file1.txt file2.txt file3.txt
```

It creates `file2.txt` and `file3.txt`, when it should actually create no new files.

**Comment by dthree** [comment]
I think that's a Vorpal parsing bug, where it's taking `file1.txt` as a parameter of `-c`. Vorpal uses `minimist` to parse args, and minimist doesn't know the `-c` isn't expecting an argument. I've been meaning to get to this, but it means forking minimist and getting into the guts of arg parsing.

Anyway, I think its a priority, so I'll jump on it.

As a workaround, throwing all the args after the params works totally fine, i.e. `touch file1.txt file2.txt -c`.

**Comment by nfischer** [comment]
Is there really no way to specify an option should be completely Boolean (take no argument)? This is something I've actually been meaning to work around in a project I've been developing, so I'd be interested in this solution as well.

**Comment by dthree** [comment]
I just know minimist has know way of knowing, as you need the context of what options you're parsing. Minimist parses a raw string with no metadata.

Anyway, I'll let you know when I figure it out.

**Comment by nfischer** [comment]
:+1:

**Comment by dthree** [comment]
Fixed in Vorpal.

https://github.com/dthree/vorpal/commit/8c091f948be99d55bb7120233285638c620c98b1

---

Cash deps updated.
