### ISSUE TITLE
Incorrect behavior for ls

### ISSUE THREAD

**Issue by nfischer** [dthree/cash#41]
I noticed a few main issues with `ls` so far:

 1. `ls filedoesntexist` should output a message of the form `ls: cannot access filedoesntexist: No such file or directory`. Currently, it has no output.
 2. Calling `ls` with multiple arguments causes files to look kind of like directories. This has output like:
  ```
  cash $ ls README.md appveyor.yml src
  README.md:
  README.md

  appveyor.yml:
  appveyor.yml

  src:
  commands  delimiter.js  help  help.js  index.js  lib  preparser.js  util  windows.js
  ```

  whereas I would expect:
  ```
  cash $ ls README.md appveyor.yml src
  appveyor.yml README.md

  src:
  commands  delimiter.js  help  help.js  index.js  lib  preparser.js  util  windows.js
  ```
 3. Calling `ls` on non-existing files, if there are multiple arguments, treats them like empty directories:
  ```
  cash $ ls noexist1 noexist2
  noexist1:


  noexist2:

  ```
  whereas I would expect:
  ```
  cash $ ls noexist1 noexist2
  ls: cannot access noexist1: No such file or directory
  ls: cannot access noexist2: No such file or directory
  ```

I suspect solving bugs 1 and 2 will solve 3 for you.

All of this is running off the latest release of  `cash` on Ubuntu.

**Comment by dthree** [comment]
Thanks. Valid points.

**Comment by legien** [comment]
@dthree If you are good with that, I would try to fix this?

**Comment by dthree** [comment]
@legien totally, would love the help!

**Comment by dthree** [comment]
Thank you @legien !
