### ISSUE TITLE
ReferenceError: cash is not defined

### ISSUE THREAD

**Issue by nyounker** [dthree/cash#48]
I am not a native node.js user and was testing this on an 8.1 windows enterprise -N version.
 
I followed the install instructions in administrative rights. I did an install of node.js 64bit from the node.js site though the 64bit msi which would also install the npm package manager. https://nodejs.org/en/download/
after installation
first trying 
npm install cash-global -g  ( also additional question, does this add the ENV variable to the system, and if not, what is the path?)
(ps. I also tried this with npm install cash -g as well)

I verified that all modules required for package were installed. which were applied to 

```
C:\USERS\$user\AppData\Roaming\npm\node_modules\
```
When trying to run

error
```
C:\Windows\system32>node
> cash
```

```
ReferenceError: cash is not defined
    at repl:1:1
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

readline.js, domain.js, repl.js were also verified as installed afterwards to verify and still received error.  

Any ideas?

**Comment by dthree** [comment]
You ran cash from inside a node repl instance. You just need to run it without typing node first.

**Comment by dthree** [comment]
Closing this, but if you follow my instructions will fix the issue! Let me know if you have any more Qs.

**Comment by nyounker** [comment]
Thank you. Issue closed.
It seems that with the cash-global (and standard cash install) install did not set a Environment variable for the cash location for the global variable "PATH". So for future reference for other users when installing the node.js (which also installs the package manager "npm" ) 

In order to call the application you would either need to (cd) go to the C: directory and then type "cash" or go to the native install directory that it was installed in by npm OR cd to the directory C:\Users\$yourUserName\AppData\Roaming\npm\   and then type "cash".  Otherwise, you would need to manually add the previous directory to your "PATH" Environment variable to allow the application to start whenever you type "cash".


Hope this helps.

**Comment by dthree** [comment]
Cash definitely adds to path on install.
