### ISSUE TITLE
which

### ISSUE THREAD

**Issue by konsumer** [dthree/cash#5]
I love cash! A `which` command would be helpful. When I have a chance, I'd be happy to implement it. [This](https://github.com/shelljs/shelljs/blob/master/src/which.js) might be a good start to it.

**Comment by dthree** [comment]
Sure! That would be great! Feel free to ask any questions. And don't forget to vote it up in the wiki.

https://github.com/dthree/cash/wiki/Roadmap

**Comment by konsumer** [comment]
I'm not sure how to add stuff to the wiki page. I don't see an edit link.

**Comment by dthree** [comment]
Oops! I thought it defaulted to being editable. Changed it, try now.

**Comment by konsumer** [comment]
perfect. added and thumbed. thanks!

**Comment by dthree** [comment]
:+1:

**Comment by dthree** [comment]
Going to close this with favor to the roadmap! Feel free to ask any questions.

**Comment by konsumer** [comment]
:+1:
