### ISSUE TITLE
Add support for executing scripts

### ISSUE THREAD

**Issue by nfischer** [dthree/cash#51]
It'd be nice if cash supported the following sort of thing:

``` Bash
bash $ cash filename.sh # execute filename.sh, using cash, in a separate process, and return
hello world
... # all other script output from filename.sh
bash $ # it returns back to a regular prompt (bash, zsh, cmd.exe, whatever we started from)
```

**Comment by dthree** [comment]
For sure. We'd have to mature bash a little bit before it just breaks full time, but yes, we can throw in the basic support.

**Comment by dthree** [comment]
Is this different from `source` in that it's a separate process?

**Comment by nfischer** [comment]
Yup, that's the only difference. And the thought is that `source` would be within cash, and this could be done at a regular shell (instead of always entering the interactive cash shell, as is the current behavior)

**Comment by dthree** [comment]
Okay. As it would be running node from the windows shell, wouldn't running `source` work, as node is a separate process?

**Comment by nfischer** [comment]
I think the better approach is to let `cash` start an interactive shell (as it does now) and let `cash filename.sh` execute the script in a separate process.

Then we can confine `source` to be available only for interactive shells, similar to how `alias` works.

**Comment by dthree** [comment]
K. I was mainly thinking of somehow re-using some of the code. No big deal.

**Comment by nfischer** [comment]
Understandable. They could probably be very similar in implementation (and `source` actually isn't much code, it essentially just lets `vorpal` do all the work).

**Comment by dthree** [comment]
kk
