### ISSUE TITLE
Make it easier to use inside npm script

### ISSUE THREAD

**Issue by rofrol** [dthree/cash#67]
Right now I need to do this:

```
  "scripts": {
        "ls": "node -e \"console.log(require('cash')('ls -l')); process.exit();\""
  }
```

**Comment by dthree** [comment]
I think this is a problem with any Node process running in NPM scripts.

There's a discussion here about integrating Cash into NPM to handle package scripts:

https://github.com/npm/npm/issues/11291

But that's way down the road. Working it!

**Comment by rofrol** [comment]
I need to use `process.exit()` otherwise it hangs.
I don't want to just use `ls` but use cash today in npm scripts.
So I thought that to make transition easier, add some option to cash, so that we can use

```
 "scripts": {
       "watch": "cash \"browserify -w index.js && postcss -w\""
 }
```

**Comment by nfischer** [comment]
Perhaps we could implement the `-c` option. From Bash's man page:

> ```
>        -c        If the -c option is present, then commands are read from the first non-option argument command_string.  If  there  are
>                  arguments after the command_string, they are assigned to the positional parameters, starting with $0.
> ```

**Comment by rofrol** [comment]
:+1:

**Comment by nfischer** [comment]
I opened #69 to address this feature.

**Comment by danielbayley** [comment]
@rofrol Once cash can accept `-c 'input'`, then you can simply put `script-shell = cash` inside `.npmrc` and it should _just work_.
