### ISSUE TITLE
Add support for -c option

### ISSUE THREAD

**Issue by nfischer** [dthree/cash#69]
Once we start actually parsing arguments, it would be good to add support for the `-c` option to execute a string of commands.

> ```
>        -c        If the -c option is present, then commands are read from the first non-option argument command_string.  If  there  are
>                  arguments after the command_string, they are assigned to the positional parameters, starting with $0.
> ```

This should probably be implemented after #51 is done, since that involves reading commandline args.

**Comment by andreGarvin** [comment]
is this issue still open or closed ?

**Comment by nfischer** [comment]
@andreGarvin thanks for pinging, I think this is fixed by the PR

@dthree did we cut a release for this?
