### ISSUE TITLE
Trying to open vim hangs cash

### ISSUE THREAD

**Issue by QK4** [dthree/cash#73]
When I type `$ vim` or `$ vim filename`, the shell hangs for a few seconds then the window title changes to `[NO NAME] - VIM` or `filename - VIM` but vim doesn't open and I can't enter anything into the shell, ctrl+c does nothing. Have I done something wrong or is there an issue here? Possibly related to the node modules hanging to?

**Comment by dthree** [comment]
What OS and version?

**Comment by nfischer** [comment]
Tried this out on Linux. Couldn't actually get it to run any external commands. This is against the latest master branch.

I tried:

```
nate@lenovoyoga:~/programming/cash$ vim
Cash, version 0.8.0
These shell commands are defined internally.  Type `help' to see this list.
Type `help name' to find out more about the function `name'.
Use `info cash' to find out more about the shell in general.

 alias [-p] [name=[value]]                                            ls [-aAdFhilQrRStUwx1] [paths ...]
 cat [-AbeEnstTv] [files ...]                                         mkdir [-pv] [directories ...]
 cd [dir]                                                             mv [-fnv] source ... dest
 clear                                                                pwd [files ...]
 cp [-fnr] source ... dest                                            rm [-frR] [files ...]
 echo [-eE] [arg ...]                                                 sort [-chMnrR] [-o file] [files ...]
 export [-p][id=[value]]                                              source filename [arguments...]
 false                                                                tail [options] <files ...>
 grep [-bHhinqsvw] [-m max] [--silent] [--include pattern] pattern >  touch [-acm] [-d date] [-r ref] [--time word] file ...
 head [-nqv] <files ...>                                              true
 kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill>  unalias [-a] name [names ...]
 less [files ...]
```

**Comment by dthree** [comment]
That's why I was confused.

On Linux, Cash intentionally doesn't try to run external commands. And you wouldn't have Vim on Windows.

**Comment by nfischer** [comment]
You can still install vim on Windows.

Also, @dthree why not allow cash to run external commands on Linux as well? It would be useful for running commands like `git` which aren't yet implemented internally. We should still prefer the internal implementations of commands like `ls`, `cat`, etc.

**Comment by dthree** [comment]
@nfischer we can. At the time I wrote it, I was solely running Cash on Linux for development convenience, didn't expect anyone to use it on Linux when it implements... Linux.

The idea of using it in the future for package script interpretation obviously changes this, so you are correct, the implementation should be altered.

Vim probably wouldn't at the moment either way though, as interactive programs that control terminal prompting don't jive very well right now.

**Comment by nfischer** [comment]
@dthree SGTM. Yeah, using cash on Linux isn't a huge priority, day-to-day, just would be nice to have behavior be as consistent as possible cross-platform, down the road.

**Comment by dthree** [comment]
Absolutely. :+1:

**Comment by QK4** [comment]
This was on windows 7, cash 0.8.0.
I don't usually use windows but I just tried it out because I got the impression that one of the uses of cash was to use linux commands on windows for normal use.
Found it strange that this crashed it. I get that it doesn't really need to be able to launch vim, just thought it might be an issue, cheers.

**Comment by dthree** [comment]
No problem, thanks for reporting :+1:
