### ISSUE TITLE
Wiki Links Broken

### ISSUE THREAD

**Issue by popey456963** [dthree/cash#84]
[Here](https://github.com/dthree/cash/wiki/Contributing) every single link is broken.  Makes it a pain for people wanting to contribute.

**Comment by dthree** [comment]
Thanks.

The beauty of Wiki is that anyone can fix it. If you're up to it, I would love the help!

**Comment by nfischer** [comment]
Just replace `vorpaljs` with `dthree` in the link. That should fix it.

**Comment by dthree** [comment]
Fixed.
