### ISSUE TITLE
Ignore existing commands when installing cash-global

### ISSUE THREAD

**Issue by JimmyBoh** [dthree/cash#86]
Is there a way to force the installation of commands when using `cash-global`? I saw nothing in docs and couldn't find the source to see if there was anything I could try.

**Comment by dthree** [comment]
I didn't make a way for this, as this would create `path` conflicts and unexpected behavior.

What is an example use case?

**Comment by JimmyBoh** [comment]
I have `ls` installed via git tools, but not added to my path (so I cannot use it in regular cmd, but the do work in the git-enabled terminal). When trying to install, it says they already exist and skips them. How does it check if it is installed? Where in the code is that written?

**Comment by dthree** [comment]
It actually checks path, I believe with the windows `where` command, so it appears to be in your path.

**Comment by JimmyBoh** [comment]
I understand. I ended up just adding the git /usr/bin directory to the path, which means I don't get to use `cash`, but at least it keeps my box `DRY` :wink: But I love the idea of `cash`, keep up the great work!
