### ISSUE TITLE
Updating Cash

### ISSUE THREAD

**Issue by SphinxTwo** [dthree/cash#93]
How would I update my version of Cash?

**Comment by nfischer** [comment]
Hi @SphinxTwo! Here's some steps I found online for global npm packages in general (this assumes you installed cash via `npm`):

https://docs.npmjs.com/getting-started/updating-global-packages

The gist of it is you can update it by using `npm install -g cash` to install the latest version (even if you already had it installed). We haven't had an update for a while, however, so you may already have the latest :smile:

If this doesn't fix the issue for you, let me know and I'll re-open this issue. Cheers!

**Comment by SphinxTwo** [comment]
It works, thank you. You can close this issue now.
